### ISSUE TITLE
边界计算问题

### ISSUE THREAD

**Issue by Mr-Pro** [gausszhou/vue-drag-resize-rotate#11]
当做父元素限制时，父元素采用transform放大或者是缩小时调整大小边界计算存在问题
![](https://raw.githubusercontent.com/Mr-Pro/CustomerImageHosting/master/2022/gausszhou_s_20220317191142.png)

**Comment by gausszhou** [comment]
问题原因：绕过props传值的方式直接控制scale样式的话，确实是这样，组件内部是没有对【通过其他方式修改样式】这一类情况进行处理。
