### ISSUE TITLE
没有Drop事件吗？

### ISSUE THREAD

**Issue by q4speed** [gausszhou/vue-drag-resize-rotate#2]
看起来挺不错的，但是没有找到放的事件，现在只能拖，不能放吗？

**Comment by gausszhou** [comment]
> 看起来挺不错的，但是没有找到放的事件，现在只能拖，不能放吗？

没有考虑补充放置事件，您可以尝试在被拖放的时候传递数据给组件插槽

如果您不需要旋转功能的话建议使用这个组件[vue-draggable-resizable-gorkys](https://github.com/gorkys/vue-draggable-resizable-gorkys)，或者这个[vue-drag-resize]https://github.com/gausszhou/vue-drag-resize-rotate/blob/master/src/components/vue-drag-resize/index.vue

**Comment by q4speed** [comment]
我研究一下。
