### ISSUE TITLE
可以加上 将外部元素拖入对应组件内显示吗 

### ISSUE THREAD

**Issue by ziyujiahao** [gausszhou/vue-drag-resize-rotate#3]
可以加上将外部元素拖入对应组件内显示吗  类似这种拖拽效果  [vuedraggable](https://sortablejs.github.io/Vue.Draggable/#/functional)

**Comment by gausszhou** [comment]
这个组件主要针对需要获取拖放位置和旋转角度准确参数的场景，目前是没有考虑到和多个容器之间的交互的。

如果只是将外部的元素放入单个可拖拽组件内，可以尝试使用[组件插槽](https://gausszhou.github.io/vue-drag-resize-rotate/#/basic/basic-with-slots)进行实现
