### ISSUE TITLE
下载的包里面没有CSS文件

### ISSUE THREAD

**Issue by hehaozhen11** [gausszhou/vue-drag-resize-rotate#8]

**Comment by hehaozhen11** [comment]
import "@gausszhou/vue-drag-resize-rotate/vue-drag-resize-rotate.css"  依赖包里不存在CSS文件

**Comment by gausszhou** [comment]
> import "@gausszhou/vue-drag-resize-rotate/vue-drag-resize-rotate.css" 依赖包里不存在CSS文件

现在不需要引入这个css文件，之前修改了打包配置，忘了更新文档了，Sorry

**Comment by gausszhou** [comment]
更新到了 2.0.8，请使用
```
npm install @gausszhou/vue-drag-resize-rotate@2.0.8
```

**Comment by gausszhou** [comment]
404b5c46ab455c7b4d37013c9bdc66e6840c19f3 fix: 修复package.json错误，更新Readme
