### ISSUE TITLE
功能点咨询

### ISSUE THREAD

**Issue by gzg1023** [gausszhou/vue-drag-resize-rotate#9]
我看了一下和vue-draggable-resizable-gorkys功能一样的。添加了一个旋转，我也是最近需要这个功能。
关于缩放。下面这个链接，不太对吧 这个这个直接设置整个面板了。 应该是给拖拽的元素加scale吧。
应该是：translate(25px, 72px) rotate(334deg) scale(0.7) 这种格式
https://gausszhou.github.io/vue-drag-resize-rotate/#/basic/basic-scale

还有就是作者 你那边单位是直接px吗 我这边单位还想做自定义单位  在纠结提fr还是fork项目改造。webpack也想改成rollup打包。

**Comment by gausszhou** [comment]
关于缩放：我这边的需求就是容器和子元素一起缩放的，所以就直接写了。当然也可以通过再传入一个参数来只计算缩放后的鼠标位移而不实际缩放子元素的大小。(考虑改进)
[css-transform-scale-dont-scale-child-element](https://stackoverflow.com/questions/27051600/css-transform-scale-dont-scale-child-element)
关于单位：目前是直接使用px的，如果要支持自定义单位，可以再次封装，思路就是传入当前单位和px的比值，来计算鼠标位移。  (不太考虑)
关于打包 ：目前仍是webpack打包，这个我没有改动，如果后面重写成Vue3的版本，会再考虑使用其他打包方式。

> 关于项目：由于目前我这边的实际需求没有改动，所以不太会考虑增加新的feature，因此这边建议您Fork后改造。

**Comment by gzg1023** [comment]
> 关于缩放：我这边的需求就是容器和子元素一起缩放的，所以就直接写了。当然也可以通过再传入一个参数来只计算缩放后的鼠标位移而不实际缩放子元素的大小。(考虑改进) [css-transform-scale-dont-scale-child-element](https://stackoverflow.com/questions/27051600/css-transform-scale-dont-scale-child-element) 关于单位：目前是直接使用px的，如果要支持自定义单位，可以再次封装，思路就是传入当前单位和px的比值，来计算鼠标位移。 (不太考虑) 关于打包 ：目前仍是webpack打包，这个我没有改动，如果后面重写成Vue3的版本，会再考虑使用其他打包方式。
> 
> > 关于项目：由于目前我这边的实际需求没有改动，所以不太会考虑增加新的feature，因此这边建议您Fork后改造。

好吧，那需求点不太契合。我这边还是fork来修改吧。感谢回复
